APIVersion: v1.8.0
name: crawler-typo3v8
type: typo3
docroot: public
php_version: "7.2"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
nfs_mount_enabled: false
provider: default
hooks:
  post-start:
  - exec: cp build-files/AdditionalConfiguration.ddev.php public/typo3conf/AdditionalConfiguration.php
  - exec: composer install -d /var/www/html
  - exec: /var/www/html/bin/typo3cms install:generatepackagestates
  - exec: /var/www/html/bin/typo3cms install:extensionsetupifpossible
  - exec-host: ddev import-db --src=build-files/db.sql.gz
  - exec: /var/www/html/bin/typo3cms cache:flush

omit_containers: [dba]
